### ISSUE TITLE
get the mean PSF at the center of each central

### ISSUE THREAD

**Issue by moustakas** [moustakas/legacyhalos#23]
This issue is somewhat ill-posed because of the wide range of CCDs that contribute to a given coadd, but we will need the mean PSF to do the model fitting in #19, especially when we incorporate WISE (#22).  Even an approximate Gaussian sigma width may be sufficient.

**Comment by dstndstn** [comment]
grab the psfsize_[grz] fields from the LS catalogs?

**Comment by moustakas** [comment]
Excellent, yes, that's probably all we need.  Thanks @dstndstn.

**Comment by moustakas** [comment]
I've confirmed that the custom Tractor catalog has what I need to account for the band-dependent PSF.
