### ISSUE TITLE
investigate interesting failures of how we isolate the light of the central galaxy

### ISSUE THREAD

**Issue by moustakas** [moustakas/legacyhalos#24]
@dstndstn Here's an interesting failure.

In the standard analysis method for this project, I produce a coadd which has all but the central galaxy subtracted out:
![0000510-coadd-montage](https://user-images.githubusercontent.com/1431820/42162364-69d75904-7dcc-11e8-8efa-a8c9ba9118a1.png)

However, in this example, the segmentation and source deblending has gone awry, and so the whole central region is masked out, preventing ellipse-fitting:

![0000510-ellipse-multiband](https://user-images.githubusercontent.com/1431820/42162448-c0111cec-7dcc-11e8-8e0c-71933f1a7591.png)

Here's the full webpage for this object (subject to change, of course), in case you're interested:
http://portal.nersc.gov/project/cosmo/temp/ioannis/legacyhalos/0000510/0000510.html

I think what I need to do is to *not* subtract out other galaxies that are within some threshold radius of the central I'm interested in and just let their light contribute, for example:
http://portal.nersc.gov/project/cosmo/temp/ioannis/legacyhalos/0000729/0000729.html
(Well, the *ideal* solution would be to get the source deblending right!)

Here's another example of a failure:
http://portal.nersc.gov/project/cosmo/temp/ioannis/legacyhalos/0000887/0000887.html

**Comment by dstndstn** [comment]
So in this case, did that little galaxy below and to the left try to explain all the light of the central?  Is it maybe a COMP with one huge component and one compact?  I wonder if you can look for objects like that and steal the light from the large component.

I'm curious what DR7 will do with this one.

**Comment by moustakas** [comment]
This is with the DR7 code.

**Comment by dstndstn** [comment]
Ahh, okay, curiosity satified!

**Comment by moustakas** [comment]
The failures above were resolved by the algorithms implemented in #72, but here's a failure with the current version of the code:

<img width="1021" alt="screen shot 2019-02-21 at 7 45 17 pm" src="https://user-images.githubusercontent.com/1431820/53211994-43b83380-3611-11e9-80a7-e1e7e3b19bb2.png">

**Comment by moustakas** [comment]
Summary of current failures in #75.
