### ISSUE TITLE
use the blob image to mask sources...

### ISSUE THREAD

**Issue by moustakas** [moustakas/legacyhalos#43]
...not the model image.

The blob image is written to the `metrics` directory, however, which I don't currently keep/write.  Blarg.

**Comment by moustakas** [comment]
@dstndstn Without me having done any work to figure this out myself, can I get the same information from the *maskbits* image, which I *did* keep?  In other words, can I identify pixels that contain sources therein?

**Comment by moustakas** [comment]
Can I easily run the segmentation / blob-making code on the fly on a residual image?  Right now I'm doing a very boneheaded thing here of just flagging "significant" pixels in the *model* image
https://github.com/moustakas/legacyhalos/blob/master/legacyhalos/io.py#L211-L215
but I'm worried that I'm not masking aggressively enough which is affecting my ellipse fitting, especially at large radius.

**Comment by dstndstn** [comment]
Sure -- here's how that is done for the 'segment' branch:

https://github.com/legacysurvey/legacypipe/blob/master/py/legacypipe/oneblob.py#L426

You might want to take the abs() for the residual images

**Comment by moustakas** [comment]
Actually, I think the blobs are too aggressive for what we want.  In many cases the central galaxy cutouts contain only a handful of blobs, dominated of course by the blob containing the central.  So we would have to segment at a finer level anyway.

What we're doing now -- masking pixels in the *model* image above a threshold value of the sky noise (I think I'm using a very conservative ~0.5-sigma or so) plus iterative binary dilation, seems to be working reasonably well.
