### ISSUE TITLE
interesting corner cases / failures with Tractor

### ISSUE THREAD

**Issue by moustakas** [moustakas/legacyhalos#46]
@dstndstn any thoughts on what happened here?  The models overall look great, but does the boxiness come from your FFT jujitsu?

This object is [0000486](http://portal.nersc.gov/project/cosmo/temp/ioannis/legacyhalos/0000486/0000486.html), BTW, which took nearly 4 hours to process on edison with 4 cores.

<img width="974" alt="screen shot 2018-07-14 at 1 51 06 pm" src="https://user-images.githubusercontent.com/1431820/42727055-19a1b8bc-876d-11e8-9ec6-7f05b6836809.png">

**Comment by moustakas** [comment]
I'm blown away by how well that foreground elliptical is modeled!

**Comment by dstndstn** [comment]
Yuck!  Is this a fairly large cutout?  I think there is some size limit on
how big of models we render.  Would bet that box size is roughly a power of
2 pixels :)

**Comment by dstndstn** [comment]
Lookit all the crap little galaxies it put around the outside of that box!

**Comment by moustakas** [comment]
It's 1034x1034 pixels2 (150x150 kpc2).

```
python /global/cscratch1/sd/ioannis/repos/legacypipe/py/legacypipe/runbrick.py \
  --radec 153.6070569395267 -0.8718788304821169 --width 1034 --height 1034 \
  --pixscale 0.262 --threads 4
```

**Comment by moustakas** [comment]
This is 0003208:  http://legacysurvey.org/viewer/?ra=27.588640&dec=-10.091795&zoom=15&layer=decals-dr5.

It's not that this is a failure it's that another source gets all the light of the central!

<img width="976" alt="screen shot 2018-07-14 at 2 04 36 pm" src="https://user-images.githubusercontent.com/1431820/42727128-ea918514-876e-11e8-97c2-444cb8bcf7b0.png">

**Comment by moustakas** [comment]
Here are some notes of additional failures --
* 0242325 - 1306 - Tile 0136p015 band 1 -- model not found
* 0247213 - 1320 - Tile 1830m016 band 1 -- model not found
* 0319665 - 1449 - missing g-band image
* 0319665 - 1459 - tile not found

**Comment by dstndstn** [comment]
It looks like this is coming from here:

https://github.com/legacysurvey/legacypipe/blob/master/py/legacypipe/oneblob.py#L1966

You could try increasing that to 256...?

**Comment by moustakas** [comment]
Summary of current failures in #75.
