### ISSUE TITLE
'NoneType' object has no attribute 'map'

### ISSUE THREAD

**Issue by moustakas** [moustakas/legacyhalos#7]
@dstndstn 

I'm running [this mpi script](https://github.com/moustakas/legacyhalos/blob/master/bin/mpi-legacyhalos-coadds) on cori but even before it finishes [building the coadds](https://github.com/moustakas/legacyhalos/blob/master/legacyhalos/legacyhalos_coadds.py#L140) I get the following error

```
[crash]
Checking for cached splineskyfn : /global/cscratch1/sd/desiproc/dr5/calib/decam/splinesky/00559/00559022/decam-00559022-N10.fits -> /global/cscratch1/sd/desiproc/dr5/calib/decam/splinesky/00559/00559022/decam-00559022-N10.fits
Checking for cached skyfn : /global/cscratch1/sd/desiproc/dr5/calib/decam/sky/00559/00559022/decam-00559022-N10.fits -> /global/cscratch1/sd/desiproc/dr5/calib/decam/sky/00559/00559022/decam-00559022-N10.fits
decam-00559022-N10 z exptime 156.0 propid 2014B-0404 seeing 1.25 object DECaLS_46834_z                       
Cut CCDs: Wall: 0.40 s, CPU: 0.38 s
[serial tims] Finding images touching brick: Wall: 0.40 s, CPU: 0.38 s
'NoneType' object has no attribute 'map'
```
I'm using the master branch of `legacypipe` but have set 
```bash
export LEGACY_SURVEY_DIR=/global/cscratch1/sd/desiproc/dr5                                                                              
```
Any thoughts on what's going on?  Should I be using the DR5-tagged version of `legacypipe`?

**Comment by dstndstn** [comment]
I'm guessing this is coming from the multiproc object -- guessing you're passing mp=None and it's calling mp.map().  multiproc objects don't pickle, so you'll have to create a local one on each rank.

**Comment by moustakas** [comment]
Hmm, I see -- `map` is a `astrometry.util.multiproc` method and I'm not passing it.

**Comment by moustakas** [comment]
That did it!  New error (hjaking this unrelated thread) is
  File not found: '/global/cscratch1/sd/desiproc/dr5/images/decam/CP20160407/c4d_160409_074303_oki_g_v1.fits.fz'

Is there a more recent staging area for the images data?

**Comment by dstndstn** [comment]
You could try /global/cscratch1/sd/desiproc/dr5-new -- looks like the
problem with that 'dr5' directory is that the images/decam points to the
staging dir, so you need a DECam_CP/ addition to the path -- which means
that path might be in [some version of] the CCDs table already.

It also looks like we have an old symlink farm here,
/global/cscratch1/sd/desiproc/dr5/images/old_links_decam/
so you or I could swap that in for 'decam'.

**Comment by moustakas** [comment]
For the record I'm using
```
export LEGACY_SURVEY_DIR=/global/cscratch1/sd/dstn/dr5
```

New error (perhaps a Python 2-->3 problem?) --
```bash
[snip]
Getting model for Image decam-00535663-N11 g : Wall: 0.11 s, CPU: 0.11 s
tim modelMinval 0.0
Getting model for Image decam-00547830-N11 r : Wall: 0.11 s, CPU: 0.11 s
tim modelMinval 0.0
Getting model for Image decam-00559022-N10 z : Wall: 0.11 s, CPU: 0.11 s
Doing Lanczos resampling
module 'itertools' has no attribute 'imap'
```

Thoughts?

**Comment by moustakas** [comment]
Looks like this was again on my end -- not passing `multiproc` correctly again.  However, I do think this is a Python 2/3 bug in `legacypipe`.  I'll open an issue there.
